### ISSUE TITLE
Binary windows not work

### ISSUE THREAD

**Issue by NycuRO** [SalmonGER/PocketMine-MP-Binarys#5]
x86: bin\php\php.exe: Exit 127
C:/Users/user/Desktop/1/bin/php/php.exe: error while loading shared libraries: api-ms-win-crt-locale-l1-1-0.dll: cannot open shared object file: No such file or directory

x64: C:/Users/user/Desktop/1/bin/php/php.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
bin\php\php.exe: Exit 127

**Comment by Aericio** [comment]
+1+1+1 SAAAAME DUDUDDUDUDUDEEE

**Comment by Aericio** [comment]
@SalmonGER Add the php.exe file in, it was missing.

**Comment by SalmonGER** [comment]
Fixed @NycuRO @Aericio
