### ISSUE TITLE
7.0.12 binary?

### ISSUE THREAD

**Issue by NycuRO** [SalmonGER/PocketMine-MP-Binarys#6]
You can add 7.0.12 binary?

YAML 2.0.0 RELEASED OFFICIAL. @SalmonGER

**Comment by SalmonGER** [comment]
@NycuRO I know :D I'll try to compile today. (With the stable yaml 2.0.0 extension)

**Comment by NycuRO** [comment]
Ok Salami bruder 👍 💃

**Comment by SalmonGER** [comment]
Added. openssl is now also available,
